### ISSUE TITLE
Won't launch when Xamarin Studio isn't present

### ISSUE THREAD

**Issue by matthewblott** [Redth/MSSolutionLauncher#1]
I was having issues running XS and VS for Mac together as the latter requires a beta version of Mono. Anyhow, the launcher was working okay and VS for Mac seems stable enough so I uninstalled XS but now the launcher doesn't work. Previously it prompted to open the solution in either XS or VS for Mac which suggests it needs both present. I had a quick scan of the code but wondered if there's a quick workaround you know - I can do a build on my own machine if need be. Thanks in advance :-)

**Comment by matthewblott** [comment]
UPDATE: I just reinstalled XS and the launcher now works. I'll just leave XS here but I'd like to get rid of it as I only have a 250GB drive but at least it's working.

**Comment by ClimberBear** [comment]
Hi
I have found the same issue.
If you configure preferences (as explained in readme) for use directly VS, you can solve the problem.

**Comment by matthewblott** [comment]
Nice one, thanks (my bad for not reading properly).
