### ISSUE TITLE
Issue with Visual Studio for Mac 7.5.1

### ISSUE THREAD

**Issue by ali-h2010** [Redth/MSSolutionLauncher#5]
I am facing an error after updating visual studio where only one project is loaded successfully and any other project I open after the first one will fail to load as the attached image. 

It say: Load failed, no access to the given key.

https://ibb.co/iO95Ld

**Comment by chrissingh** [comment]
Ran into the same issue recently. Currently using the follow to launch another instance of VS from terminal. Will look to package that into a shortcut to add to dock in similar fashion as this MSSolutionLauncher.

open -n "/Applications/Visual Studio.app"

**Comment by ali-h2010** [comment]
@chrissingh I tried to make this as a script but it doesn't work. It's very easy to make a patch file in windows to call this in the command prompt. 

I didn't try with backslashes though . Thanks for the update.

**Comment by chrissingh** [comment]
I was able to get this wrapped with Automator. I selected Run Shell Script. Added
 open -n "/Applications/Visual Studio.app" as the command. Did an export from Automator and saved as VSLauncher.app. 

For Icon I copied the current MSSolutionLauncher. Reference: https://apple.stackexchange.com/questions/369/can-i-change-the-application-icon-of-an-automator-script

**Comment by ali-h2010** [comment]
@chrissingh Thank you so much for the great idea. 
I used this command in the automator without backslashes and .app
`open -n -a "Visual Studio"`

**Comment by ali-h2010** [comment]
@chrissingh 
I think I spoke too soon.
When I set the app as the default for lunching *.sln , it just opens a new instance of Visual studio and not the solution. 
I am not sure if it works as expected on your side.

**Comment by EsmerlinMoya** [comment]
I was looking for this solution

**Comment by cosminstirbu** [comment]
I've logged on issue on VS for Mac as well.

https://developercommunity.visualstudio.com/content/problem/257224/vs-for-mac-version-751-build-22-broke-ms-solution.html

Not sure if it's a MS Solution Launcher Issue or a VS for Mac "breaking" change.

**Comment by nleach7** [comment]
👍  I'm glad I'm not the only one with this issue. I thought I was going crazy!

**Comment by mrward** [comment]
This does not seem to be a problem with the MS Solution Launcher. It is a problem with the IoT 7.5 extension. If you disable or uninstall the IoT extension then the MS Solution Launcher works. The IoT 7.0 extension is OK.

The underlying problem seems to be that the IoT 7.5 extension is shipping a Windows specific version of the System.Runtime.InteropServices.RuntimeInformation assembly. This then results in MSBuild thinking it is on Windows. MSBuild then runs some code that throws an exception after it tries to access the `/Library/Application Support/com.altusapps.mssolutionlauncher` directory. So we should be able to fix this by changing the IoT extension. //cc @Redth

**Comment by chrissingh** [comment]
@mrward  is right. I was able to disable the IOT extension and it solved the issue.

**Comment by cbartonnh** [comment]
Thanks @mrward for figuring this one out. Never would have guessed what it turned out to be.

**Comment by mws580** [comment]
there is an update for the IoT extension.  I ran the update and restarted VS with MS Launcher and it works now!!

**Comment by mrward** [comment]
Xamarin.IoT 7.5.3, which was released yesterday, is no longer shipping extra MSBuild assemblies so that version does not break the launcher.
